server:
  port: 8080
spring:
  base:
    datasource:
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:postgresql://localhost:16000/monitor_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:migrations/master.xml
    user: liquibase_user
    password: password
  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    web: DEBUG
