server:
  port: 8080
spring:
  base:
    datasource:
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:postgresql://localhost:16000/monitor_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console
  liquibase:
    enabled: true
    change-log: classpath:migrations/master.xml
    user:
    password:
  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: false
